obj-$(CONFIG_NTR_TIMER)	+= ntr_timer.o
obj-$(CONFIG_NTR_IRQC)	+= ntr_irqc.o

# obj-$(CONFIG_NTR_SLOT1)	+= ntr_slot1.o

obj-$(CONFIG_NTR_DEBUG_EARLYCON) += ntr_earlycon.o
obj-$(CONFIG_SERIAL_IS_SPI_USB_ADAPTER)	+= is-spi-usb-adapter.o
